In [4]:
import requests
from PIL import Image
import numpy as np
import cv2
from io import BytesIO

# List of image URLs (you can replace these with your own URLs)
image_urls = [
    "https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpeg",
    "https://cdn.pixabay.com/photo/2015/10/09/00/55/lotus-978659_640.jpg",
    "https://s28151.pcdn.co/wp-content/uploads/sites/2/2022/03/Coyote-animal-sentience-research.jpg",
    "https://i.natgeofe.com/k/9acd2bad-fb0e-43a8-935d-ec0aefc60c2f/monarch-butterfly-grass_3x2.jpg",
    "https://image.shutterstock.com/image-photo/green-leaves-philodendron-plant-nature-260nw-2477697533.jpg"
]

# Download images
images = []
for url in image_urls:
    response = requests.get(url)
    img = Image.open(BytesIO(response.content))
    images.append(img)

# Resize images to 256x256 pixels
resized_images = [img.resize((256, 256)) for img in images]

# Convert images to grayscale
gray_images = [cv2.cvtColor(np.array(img), cv2.COLOR_RGB2GRAY) for img in resized_images]

# Extract boundary features using Canny edge detection
boundary_features = [cv2.Canny(img, 100, 200) for img in gray_images]

# Extract region features (using image moments)
region_features = [cv2.moments(img) for img in gray_images]

# Convert region features to a feature vector (example with centroid x, y)
feature_vectors = []
for moments in region_features:
    if moments["m00"] != 0:
        cx = int(moments["m10"] / moments["m00"])
        cy = int(moments["m01"] / moments["m00"])
    else:
        cx, cy = 0, 0
    feature_vectors.append([cx, cy])

# Display results
print("Boundary Features (Canny edges):")
for i, bf in enumerate(boundary_features):
    print(f"Image {i+1}:")
    print(bf)

print("\nRegion Features (Centroid coordinates):")
for i, fv in enumerate(feature_vectors):
    print(f"Image {i+1}: Centroid = {fv}")

print("\nFeature Vectore:")
print(feature_vectors)

Boundary Features (Canny edges):
Image 1:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Image 2:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Image 3:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Image 4:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Image 5:
[[  0 255   0 ...   0   0   0]
 [  0 255   0 ...   0   0   0]
 [  0 255   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]

Region Features (Centroid coordinates):
Image 1: Centroid = [117, 139]
Image 2: Centroid = [120, 124]
Image 3: Centroid = [129, 132]
Image 4: Centroid = [131, 122]
Image 5: Centroid = [130, 131]

Feature Vectore:
[[117, 139], [120, 124], [129, 132],