In [4]:
import numpy as np

In [1]:
# Step 1: Define the samples for each class
X1 = np.array([[6, 4], [4, 5], [3, 4], [5, 7], [6, 6]])
X2 = np.array([[11, 12], [7, 9], [10, 7], [10, 9], [12, 10]])

# Step 2: Compute the mean vectors
mu1 = np.mean(X1, axis=0)
mu2 = np.mean(X2, axis=0)

mu1, mu2

(array([4.8, 5.2]), array([10. ,  9.4]))

In [2]:
# Step 3: Compute the within-class scatter matrix SW
S_W = np.zeros((2, 2))

# Compute the scatter matrix for class ω1
for x in X1:
    diff = (x - mu1).reshape(2, 1)
    S_W += diff @ diff.T

# Compute the scatter matrix for class ω2
for x in X2:
    diff = (x - mu2).reshape(2, 1)
    S_W += diff @ diff.T

# Step 4: Compute the between-class scatter matrix SB
diff_mu = (mu1 - mu2).reshape(2, 1)
S_B = diff_mu @ diff_mu.T

S_W, S_B

(array([[20.8,  7.2],
        [ 7.2, 20. ]]),
 array([[27.04, 21.84],
        [21.84, 17.64]]))

In [3]:
# Step 5: Compute the eigenvalues and eigenvectors of SW^-1 * SB
# First, compute the inverse of SW
S_W_inv = np.linalg.inv(S_W)

# Then, compute the matrix SW^-1 * SB
S_W_inv_S_B = S_W_inv @ S_B

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(S_W_inv_S_B)

# Find the eigenvector corresponding to the largest eigenvalue
max_eigenvalue_index = np.argmax(eigenvalues)
linear_discriminant_vector = eigenvectors[:, max_eigenvalue_index]

eigenvalues, linear_discriminant_vector

(array([ 1.62899824e+00, -1.72447039e-16]), array([0.82816079, 0.5604906 ]))